name: ios
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  pinput: ^5.0.1
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.6
  cloud_functions: ^5.5.0
  firebase_storage: ^12.4.5
  google_fonts: ^4.0.4
  google_sign_in: ^6.1.5
  font_awesome_flutter: ^10.8.0
  image_picker: ^1.0.4
  uuid: ^4.2.1
  intl: ^0.18.1
  http: ^1.3.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - Assets/aboutUS1.png
    - Assets/aboutUS2.png
    - Assets/backgroundimg.png
    - Assets/child1.png
    - Assets/child2.png
    - Assets/child3.png
    - Assets/child4.png
    - Assets/child5.png
    - Assets/child6.png
    - Assets/child7.png
    - Assets/child8.png
    - Assets/Completed_Icon.png
    - Assets/google.png
    - Assets/homeimg1.png
    - Assets/homeimg2.png
    - Assets/act.png
    - Assets/help.png
    - Assets/JustLogo.png
    - Assets/logo.png
    - Assets/sad-face.png
    - Assets/l1.png
    - Assets/l2.png
    - Assets/l3.png
    - Assets/admin1.png
    - Assets/admin2.png
    - Assets/admin3.png
    - Assets/admin4.png
    - Assets/icons/
